### ISSUE TITLE
After Update: "Application cannot be started" (OS Build 14393.969)

### ISSUE THREAD

**Issue by stroborobo** [uxsoft/AppleWirelessKeyboard#5]
On application start there's a popup saying "Application cannot be started. Contact the application vendor.". Clicking the Details button shows this:

```
PLATFORM VERSION INFO
	Windows 			: 10.0.14393.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.6.1586.0 built by: NETFXREL2
	clr.dll 			: 4.6.1637.0 built by: NETFXREL3STAGE
	dfdll.dll 			: 4.6.1586.0 built by: NETFXREL2
	dfshim.dll 			: 10.0.14393.0 (rs1_release.160715-1616)

SOURCES
	Deployment url			: file:///C:/Users/bo/AppData/Roaming/Microsoft/Windows/Start%20Menu/Programs/uxsoft/AppleWirelessKeyboard/AppleWirelessKeyboard.appref-ms%7C
						Server		: Microsoft-IIS/8.0
						X-Powered-By	: ASP.NET
	Deployment Provider url		: http://clients.uxsoft.cz/awk/AppleWirelessKeyboard.application

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of C:\Users\bo\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\uxsoft\AppleWirelessKeyboard\AppleWirelessKeyboard.appref-ms| resulted in exception. Following failure messages were detected:
		+ The deployment identity does not match the subscription.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	* The manifest for this application does not have a signature. Signature validation will be ignored.

OPERATION PROGRESS STATUS
	* [2017-03-27 09:20:45] : Activation of C:\Users\bo\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\uxsoft\AppleWirelessKeyboard\AppleWirelessKeyboard.appref-ms| has started.
	* [2017-03-27 09:20:45] : Performing necessary update check as specified by the deployment.

ERROR DETAILS
	Following errors were detected during this operation.
	* [2017-03-27 09:20:45] System.Deployment.Application.DeploymentException (SubscriptionState)
		- The deployment identity does not match the subscription.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.SubscriptionStore.CheckUpdateInManifest(SubscriptionState subState, Uri updateCodebaseUri, AssemblyManifest deployment, Version currentVersion, Boolean& bUpdateInPKTGroup)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentUpdate(SubscriptionState& subState, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ProcessOrFollowShortcut(String shortcutFile, String& errorPageUrl, TempFile& deployFile)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.
```

**Comment by stroborobo** [comment]
Ok, reinstalled form the pre-built setup.exe, now it starts, but doesn't work and crashes again after a couple seconds.

**Comment by stroborobo** [comment]
Oh sorry, reinstall worked, but it removed my configuration, upon looking it up it crashed, but otherwise it's working now. Nevermind :)
